FROM quay.io/pires/docker-elasticsearch:5.4.1

# RUN /usr/share/elasticsearch/bin/plugin install --batch royrusso/elasticsearch-HQ
# RUN /usr/share/elasticsearch/bin/plugin install --batch lmenezes/elasticsearch-kopf
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-attachment