version: '2'

services:
  wordpress:
    build: ./wp-docker
    volumes:
      - proud-native-osx-sync:/var/www/html:nocopy # nocopy is important
#      - ./wp-docker/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
      - elasticsearch
      - elasticdocapi
    links:
      - db:mysql
      - "elasticsearch:elasticsearchdocs.elasticsearch"
      - "elasticdocapi:docsapi.elasticsearch"
    ports:
      - 8000:80
    networks:
      - default
      - es-net
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: HELLO
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: proud.local,sub.proud.local,library.proud.local
      ELASTICSEARCH_HOST: "elasticsearchdocs.elasticsearch"
      ELASTICSEARCH_DOCS_HOST: "docsapi.elasticsearch"


  db:
    image: mariadb
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: HELLO

  # nginx:
  #   image: jwilder/nginx-proxy
  #   ports:
  #    - 80:80
  #   volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro

  redis:
    image: redis
    restart: always
    networks:
      - es-net
    ports:
        - 6379:6379

  elasticdocapi:
    build: ./proud-elastic-doc-api
    restart: always
    ports: 
      - 8085:80
    depends_on:
      - redis
    links:
      - "redis:elasticdocsapiredis.elasticsearch"
      - "elasticsearch:elasticsearchdocs.elasticsearch"
    networks:
      - es-net
    environment:
      PORT: 80
      ELASTIC: "elasticsearchdocs.elasticsearch"
      REDIS: "elasticdocsapiredis.elasticsearch"
      REDISPORT: 6379

  elasticsearch:
    image: quay.io/pires/docker-elasticsearch:5.3.2
    volumes:
      - ./elastic/data:/data
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ES_PLUGINS_INSTALL=ingest-attachment"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 2g
    privileged: true
    ports:
      - 9200:9200
    networks:
      - es-net

networks:
  default:
  es-net:

volumes:
  proud-native-osx-sync:
    external: true